### ISSUE TITLE
python supported versions

### ISSUE THREAD

**Issue by sobalgi** [pedemonte96/causaleffect#3]
Hello,

Congratulations on the implementation of `causaleffect` package in python. I have been looking for a python port of `causaleffect` package in R and your work looks wonderful and I wanted to give it a try!

However I'm unable to install the package using pip in my conda environment due to the following error message.

``
~$ python -V
Python 3.6.10 :: Anaconda, Inc.

~$ pip install causaleffect
ERROR: Could not find a version that satisfies the requirement causaleffect (from versions: none)
ERROR: No matching distribution found for causaleffect
``

I suspect it might be due to the python version.

Please let me know if I'm doing something wrong with the installation.

I was able to install python-igraph using pip from `requirements.txt` but not the causaleffect package from pip.

**Comment by pedemonte96** [comment]
Dear,

First of all, thank you for your kind words.

This package has been developed for python 3.7 or above, this might be the issue you encounter. Additionally, try installing it with 
```
python -m pip install causaleffect

```

Try to update python and please tell me if it still fails!
